name: Generate PDF from Markdown

on:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node JS
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: npm i md-to-pdf bootstrap github-markdown-css
      - name: Generate
        run: node_modules/.bin/md-to-pdf --config-file config.json README.md 
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: RodionGudz-CV
          path: RodionGudz-CV.pdf
