name: Generate PDF from Markdown

on:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node JS
        uses: actions/setup-node@v2
        with:
          node-version: latest
      - name: Install dependencies
        run: npm i -g md-to-pdf bootstrap github-markdown-css
      - name: Generate
        run: cat READNE.md | md-to-pdf > RodionGudz-CV.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: "RodionGudz-CV.pdf"
          path: RodionGudz-CV.pdf
